import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './_styles/globals.scss';
import Header from './_components/Header';

const notoSansKR = localFont({
  src: [
    {
      path: './fonts/NotoSansKR-Light.woff',
      weight: '300',
      style: 'normal',
    },
    {
      path: './fonts/NotoSansKR-Regular.woff',
      weight: '400',
      style: 'normal',
    },
    {
      path: './fonts/NotoSansKR-Medium.woff',
      weight: '500',
      style: 'normal',
    },
    {
      path: './fonts/NotoSansKR-Bold.woff',
      weight: '700',
      style: 'normal',
    },
  ],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='ko'>
      <body className={`${notoSansKR.className}`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
