import type { Metadata } from "next";
import localFont from "next/font/local";
import Header from "./_components/Header";
import GlobalLayout from "./_layout/GlobalLayout";

import "./globals.css";
import DarkModeInitializer from "./_components/shared/DarkModeInitializer";

const notoSansKR = localFont({
  src: [
    {
      path: "./fonts/NotoSansKR-Light.woff",
      weight: "300",
      style: "normal",
    },
    {
      path: "./fonts/NotoSansKR-Regular.woff",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/NotoSansKR-Medium.woff",
      weight: "500",
      style: "normal",
    },
    {
      path: "./fonts/NotoSansKR-Bold.woff",
      weight: "700",
      style: "normal",
    },
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" className="dark">
      <body className={`${notoSansKR.className}`}>
        <DarkModeInitializer />
        <Header />
        <GlobalLayout>{children}</GlobalLayout>
      </body>
    </html>
  );
}
